### ISSUE TITLE
about espnet/wsj0_mix_spatialized

### ISSUE THREAD

**Issue by shanhaidexiamo** [Emrys365/alfred_workflows#1]
您好，请问在espnet的wsj0_mix_spatialized代码中，我运行的SDR结果大概在10-11dB，我运行了两次都是类似的结果，这是正常的吗？不知道系统默认的是不是双通道？因为双通道中您的结果高达20dB, 望解惑，谢谢您。

**Comment by Emrys365** [comment]
你好，你跑的应该是 egs2/wsj0_2mix_spatialized/enh1 的 recipe？这个实验结果中默认用的全部通道（即 8 通道），我跑的 anechoic 数据的结果和你的结果是类似的。

此外我测试过 anechoic 数据上用默认的所有通道（8 ch）训练的性能是比只用前 2 个通道要差的，所以在 README.md 中放的是用 2 ch 跑出来的最好结果。

如果想只使用前 2 个通道，你需要手动修改模型中的数据维度：https://github.com/espnet/espnet/blob/master/espnet2/enh/layers/dnn_beamformer.py#L252 

```python
data = data.permute(0, 3, 2, 1) → data = data.permute(0, 3, 2, 1)[:, :, :2]
```

后面我们会更新 README.md 里面的内容，你可以跟这个最近我们复现的结果（https://github.com/kqwyf/espnet/blob/wsj0_2mix_spatialized/egs2/wsj0_2mix_spatialized/enh1/README.md）进行比较，其中表格的前两行和你的结果应该是对应的。

> PS: 这个仓库跟 espnet 无关的，你的问题可以在这里提：https://github.com/Emrys365/espnet/issues

**Comment by shanhaidexiamo** [comment]
好的好的，谢谢师兄，我是没找到相关的提问链接，看到了您的这个项目才过来提问的。非常感谢您的解答。看起来双通道要比八通道效果更好，这个是我没想到的，例论上通道数增加效果应该会更好才对，，挺奇怪。再次谢谢
